### PR TITLE
chore: merge upstream 0.4.0 as 0.4.0-sk

### PR DESCRIPTION
**Pull request by zbaylin**

### CODE REVIEW

**Review by sktrent — COMMENTED** [review]
Looks like mostly formatting changes -- do you know what else has changed in this release?

**Comment by zbaylin** [comment]
Well considering I'm the one that contributed all the upstream changes (that were already available in this fork), I don't think there is anything other than small formatting stuff. You can see all the commits here https://github.com/yawaramin/ocaml-decimal/compare/v0.3.1...v0.4.0

**Review by akama — APPROVED** [review]
This looks good (basically all formating?) but I do think we want to think about how in the future we should pr these types of changes a bit more. Particularly because this is a core library. I am open to suggestions. 

Also are we running these tests in ci? Either in this repo or in main?

**Comment by zbaylin** [comment]
No the tests aren't run automatically but we probably could. I can work on that sometime soon.

**Pull request merged**
